In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/content/train-chennai-sale.csv')

In [3]:
df

,PRT_ID,AREA,INT_SQFT,DATE_SALE,DIST_MAINROAD,N_BEDROOM,N_BATHROOM,N_ROOM,SALE_COND,PARK_FACIL,...,UTILITY_AVAIL,STREET,MZZONE,QS_ROOMS,QS_BATHROOM,QS_BEDROOM,QS_OVERALL,REG_FEE,COMMIS,SALES_PRICE
0,P03210,Karapakkam,1004,04-05-2011,131,1.0,1.0,3,AbNormal,Yes,...,AllPub,Paved,A,4.0,3.9,4.9,4.330,380000,144400,7600000
1,P09411,Anna Nagar,1986,19-12-2006,26,2.0,1.0,5,AbNormal,No,...,AllPub,Gravel,RH,4.9,4.2,2.5,3.765,760122,304049,21717770
2,P01812,Adyar,909,04-02-2012,70,1.0,1.0,3,AbNormal,Yes,...,ELO,Gravel,RL,4.1,3.8,2.2,3.090,421094,92114,13159200
3,P05346,Velachery,1855,13-03-2010,14,3.0,2.0,5,Family,No,...,NoSewr,Paved,I,4.7,3.9,3.6,4.010,356321,77042,9630290
4,P06210,Karapakkam,1226,05-10-2009,84,1.0,1.0,3,AbNormal,Yes,...,AllPub,Gravel,C,3.0,2.5,4.1,3.290,237000,74063,7406250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7104,P03834,Karapakkam,598,03-01-2011,51,1.0,1.0,2,AdjLand,No,...,ELO,No Access,RM,3.0,2.2,2.4,2.520,208767,107060,5353000
7105,P10000,Velachery,1897,08-04-2004,52,3.0,2.0,5,Family,Yes,...,NoSeWa,No Access,RH,3.6,4.5,3.3,3.920,346191,205551,10818480
7106,P09594,Velachery,1614,25-08-2006,152,2.0,1.0,4,Normal Sale,No,...,NoSeWa,Gravel,I,4.3,4.2,2.9,3.840,317354,167028,8351410
7107,P06508,Karapakkam,787,03-08-2009,40,1.0,1.0,2,Partial,Yes,...,ELO,Paved,RL,4.6,3.8,4.1,4.160,425350,119098,8507000
7108,P09794,Velachery,1896,13-07-2005,156,3.0,2.0,5,Partial,Yes,...,ELO,Paved,I,3.1,3.5,4.3,3.640,349177,79812,9976480

In [4]:
df.columns #viewing column names

Index(['PRT_ID', 'AREA', 'INT_SQFT', 'DATE_SALE', 'DIST_MAINROAD', 'N_BEDROOM',
       'N_BATHROOM', 'N_ROOM', 'SALE_COND', 'PARK_FACIL', 'DATE_BUILD',
       'BUILDTYPE', 'UTILITY_AVAIL', 'STREET', 'MZZONE', 'QS_ROOMS',
       'QS_BATHROOM', 'QS_BEDROOM', 'QS_OVERALL', 'REG_FEE', 'COMMIS',
       'SALES_PRICE'],
      dtype='object')

In [5]:
pd.set_option('display.max_columns', None) #displays all columns henceforth

In [6]:
df.PRT_ID.nunique()

7109

In [7]:
df.set_index('PRT_ID', inplace=True) # Setting 'PRT_ID' column as the index

In [9]:
df.info() # to check which are the columns in Object Dtype

<class 'pandas.core.frame.DataFrame'>
Index: 7109 entries, P03210 to P09794
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   AREA           7109 non-null   object
 1   INT_SQFT       7109 non-null   int64
 2   DATE_SALE      7109 non-null   object
 3   DIST_MAINROAD  7109 non-null   int64
 4   N_BEDROOM      7108 non-null   float64
 5   N_BATHROOM     7104 non-null   float64
 6   N_ROOM         7109 non-null   int64
 7   SALE_COND      7109 non-null   object
 8   PARK_FACIL     7109 non-null   object
 9   DATE_BUILD     7109 non-null   object
 10  BUILDTYPE      7109 non-null   object
 11  UTILITY_AVAIL  7109 non-null   object
 12  STREET         7109 non-null   object
 13  MZZONE         7109 non-null   object
 14  QS_ROOMS       7109 non-null   float64
 15  QS_BATHROOM    7109 non-null   float64
 16  QS_BEDROOM     7109 non-null   float64
 17  QS_OVERALL     7061 non-null   float64
 18  REG_FEE        7109 non-null   int64
 19  COMMIS         7109 non-null   int64
 20  SALES_PRICE    7109 non-null   int64
dtypes: float64(6), int64(6), object(9)
memory usage: 1.4+ MB

In [10]:
df # Col"PRT_ID" has become 'index column' & all columns are visible in max view

,AREA,INT_SQFT,DATE_SALE,DIST_MAINROAD,N_BEDROOM,N_BATHROOM,N_ROOM,SALE_COND,PARK_FACIL,DATE_BUILD,BUILDTYPE,UTILITY_AVAIL,STREET,MZZONE,QS_ROOMS,QS_BATHROOM,QS_BEDROOM,QS_OVERALL,REG_FEE,COMMIS,SALES_PRICE
PRT_ID,,,,,,,,,,,,,,,,,,,,,
P03210,Karapakkam,1004,04-05-2011,131,1.0,1.0,3,AbNormal,Yes,15-05-1967,Commercial,AllPub,Paved,A,4.0,3.9,4.9,4.330,380000,144400,7600000
P09411,Anna Nagar,1986,19-12-2006,26,2.0,1.0,5,AbNormal,No,22-12-1995,Commercial,AllPub,Gravel,RH,4.9,4.2,2.5,3.765,760122,304049,21717770
P01812,Adyar,909,04-02-2012,70,1.0,1.0,3,AbNormal,Yes,09-02-1992,Commercial,ELO,Gravel,RL,4.1,3.8,2.2,3.090,421094,92114,13159200
P05346,Velachery,1855,13-03-2010,14,3.0,2.0,5,Family,No,18-03-1988,Others,NoSewr,Paved,I,4.7,3.9,3.6,4.010,356321,77042,9630290
P06210,Karapakkam,1226,05-10-2009,84,1.0,1.0,3,AbNormal,Yes,13-10-1979,Others,AllPub,Gravel,C,3.0,2.5,4.1,3.290,237000,74063,7406250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P03834,Karapakkam,598,03-01-2011,51,1.0,1.0,2,AdjLand,No,15-01-1962,Others,ELO,No Access,RM,3.0,2.2,2.4,2.520,208767,107060,5353000
P10000,Velachery,1897,08-04-2004,52,3.0,2.0,5,Family,Yes,11-04-1995,Others,NoSeWa,No Access,RH,3.6,4.5,3.3,3.920,346191,205551,10818480
P09594,Velachery,1614,25-08-2006,152,2.0,1.0,4,Normal Sale,No,01-09-1978,House,NoSeWa,Gravel,I,4.3,4.2,2.9,3.840,317354,167028,8351410
P06508,Karapakkam,787,03-08-2009,40,1.0,1.0,2,Partial,Yes,11-08-1977,Commercial,ELO,Paved,RL,4.6,3.8,4.1,4.160,425350,119098,8507000
P09794,Velachery,1896,13-07-2005,156,3.0,2.0,5,Partial,Yes,24-07-1961,Others,ELO,Paved,I,3.1,3.5,4.3,3.640,349177,79812,9976480

In [11]:
df.AREA.unique()

array(['Karapakkam', 'Anna Nagar', 'Adyar', 'Velachery', 'Chrompet',
       'KK Nagar', 'TNagar', 'T Nagar', 'Chrompt', 'Chrmpet', 'Karapakam',
       'Ana Nagar', 'Chormpet', 'Adyr', 'Velchery', 'Ann Nagar',
       'KKNagar'], dtype=object)

In [14]:
df["AREA"]=df["AREA"].apply(lambda i:"Chrompet" if (i=="Chrompt" or i=="Chrmpet" or i=="Chormpet") else i) # Chrompet spellcheck

In [13]:
df["AREA"]=df["AREA"].apply(lambda i:"Anna Nagar" if (i=="Ana Nagar" or i=="Ann Nagar") else i) #Anna Nagar spellcheck

In [15]:
df["AREA"] = df["AREA"].replace({
    "Karapakam":"Karapakkam",
    "Adyr":"Adyar",
    "Velchery": "Velachery",
    "KKNagar": "KK Nagar",
    "TNagar" : "T Nagar"
}) # Remaining spellcheck

In [16]:
df.AREA.unique() # Spellings correction checked

array(['Karapakkam', 'Anna Nagar', 'Adyar', 'Velachery', 'Chrompet',
       'KK Nagar', 'T Nagar'], dtype=object)

In [17]:
from sklearn.preprocessing import LabelEncoder

a = LabelEncoder()
df["AREA_encoded"] = a.fit_transform(df["AREA"])

In [18]:
df # Column Area encoded & added to the last

,AREA,INT_SQFT,DATE_SALE,DIST_MAINROAD,N_BEDROOM,N_BATHROOM,N_ROOM,SALE_COND,PARK_FACIL,DATE_BUILD,BUILDTYPE,UTILITY_AVAIL,STREET,MZZONE,QS_ROOMS,QS_BATHROOM,QS_BEDROOM,QS_OVERALL,REG_FEE,COMMIS,SALES_PRICE,AREA_encoded
PRT_ID,,,,,,,,,,,,,,,,,,,,,,
P03210,Karapakkam,1004,04-05-2011,131,1.0,1.0,3,AbNormal,Yes,15-05-1967,Commercial,AllPub,Paved,A,4.0,3.9,4.9,4.330,380000,144400,7600000,4
P09411,Anna Nagar,1986,19-12-2006,26,2.0,1.0,5,AbNormal,No,22-12-1995,Commercial,AllPub,Gravel,RH,4.9,4.2,2.5,3.765,760122,304049,21717770,1
P01812,Adyar,909,04-02-2012,70,1.0,1.0,3,AbNormal,Yes,09-02-1992,Commercial,ELO,Gravel,RL,4.1,3.8,2.2,3.090,421094,92114,13159200,0
P05346,Velachery,1855,13-03-2010,14,3.0,2.0,5,Family,No,18-03-1988,Others,NoSewr,Paved,I,4.7,3.9,3.6,4.010,356321,77042,9630290,6
P06210,Karapakkam,1226,05-10-2009,84,1.0,1.0,3,AbNormal,Yes,13-10-1979,Others,AllPub,Gravel,C,3.0,2.5,4.1,3.290,237000,74063,7406250,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P03834,Karapakkam,598,03-01-2011,51,1.0,1.0,2,AdjLand,No,15-01-1962,Others,ELO,No Access,RM,3.0,2.2,2.4,2.520,208767,107060,5353000,4
P10000,Velachery,1897,08-04-2004,52,3.0,2.0,5,Family,Yes,11-04-1995,Others,NoSeWa,No Access,RH,3.6,4.5,3.3,3.920,346191,205551,10818480,6
P09594,Velachery,1614,25-08-2006,152,2.0,1.0,4,Normal Sale,No,01-09-1978,House,NoSeWa,Gravel,I,4.3,4.2,2.9,3.840,317354,167028,8351410,6
P06508,Karapakkam,787,03-08-2009,40,1.0,1.0,2,Partial,Yes,11-08-1977,Commercial,ELO,Paved,RL,4.6,3.8,4.1,4.160,425350,119098,8507000,4
P09794,Velachery,1896,13-07-2005,156,3.0,2.0,5,Partial,Yes,24-07-1961,Others,ELO,Paved,I,3.1,3.5,4.3,3.640,349177,79812,9976480,6

In [19]:
df.SALE_COND.unique()

array(['AbNormal', 'Family', 'Partial', 'AdjLand', 'Normal Sale',
       'Ab Normal', 'Partiall', 'Adj Land', 'PartiaLl'], dtype=object)

In [20]:
df["SALE_COND"] = df["SALE_COND"].replace({
    "Ab Normal": "AbNormal",
    "PartiaLl": "Partial",
    "Partiall" : "Partial",
    "Adj Land" : "AdjLand"
}) # SALE_COND column titles spellcheck done

In [21]:
df.SALE_COND.unique()

array(['AbNormal', 'Family', 'Partial', 'AdjLand', 'Normal Sale'],
      dtype=object)

In [22]:
from sklearn.preprocessing import LabelEncoder

b = LabelEncoder()
df["SALE_COND_encoded"] = b.fit_transform(df["SALE_COND"]) # Column SALE_COND is encoded

In [23]:
df.PARK_FACIL.unique()

array(['Yes', 'No', 'Noo'], dtype=object)

In [24]:
df["PARK_FACIL"] = df["PARK_FACIL"].replace({
    "Noo": "No"
})

In [25]:
df.PARK_FACIL.nunique() # PARK_FACIL column cleaned & type count checked

2

In [26]:
from sklearn.preprocessing import LabelEncoder

c = LabelEncoder()
df["PARK_FACIL_encoded"] = c.fit_transform(df["PARK_FACIL"])

In [27]:
df.BUILDTYPE.unique()

array(['Commercial', 'Others', 'Other', 'House', 'Comercial'],
      dtype=object)

In [28]:
df["BUILDTYPE"] = df["BUILDTYPE"].replace({
    "Comercial": "Commercial",
    "Other": "Others"
})

In [29]:
df.BUILDTYPE.unique() # Spellcheck executed

array(['Commercial', 'Others', 'House'], dtype=object)

In [30]:
from sklearn.preprocessing import LabelEncoder

d = LabelEncoder()
df["BUILDTYPE_encoded"] = d.fit_transform(df["BUILDTYPE"])

In [31]:
df.UTILITY_AVAIL.unique()

array(['AllPub', 'ELO', 'NoSewr ', 'NoSeWa', 'All Pub'], dtype=object)

In [34]:
df["UTILITY_AVAIL"] = df["UTILITY_AVAIL"].replace({
    "AllPub": "All Pub",
    "NoSewr ": "NoSeWa",
})

In [35]:
df.UTILITY_AVAIL.unique()

array(['All Pub', 'ELO', 'NoSeWa'], dtype=object)

In [36]:
from sklearn.preprocessing import LabelEncoder

e = LabelEncoder()
df["UTILITY_AVAIL_encoded"] = e.fit_transform(df["UTILITY_AVAIL"])

In [37]:
df.STREET.unique()

array(['Paved', 'Gravel', 'No Access', 'Pavd', 'NoAccess'], dtype=object)

In [38]:
df["STREET"] = df["STREET"].replace({
    "Pavd": "Paved",
    "NoAccess": "No Access",
})

In [39]:
df.STREET.nunique()

3

In [40]:
from sklearn.preprocessing import LabelEncoder

f = LabelEncoder()
df["STREET_encoded"] = f.fit_transform(df["STREET"])

In [41]:
df.MZZONE.unique()

array(['A', 'RH', 'RL', 'I', 'C', 'RM'], dtype=object)

In [42]:
from sklearn.preprocessing import LabelEncoder

g = LabelEncoder()
df["MZZONE_encoded"] = g.fit_transform(df["MZZONE"])

In [44]:
df # viewing all Spelling corrections & encoded columns

,AREA,INT_SQFT,DATE_SALE,DIST_MAINROAD,N_BEDROOM,N_BATHROOM,N_ROOM,SALE_COND,PARK_FACIL,DATE_BUILD,BUILDTYPE,UTILITY_AVAIL,STREET,MZZONE,QS_ROOMS,QS_BATHROOM,QS_BEDROOM,QS_OVERALL,REG_FEE,COMMIS,SALES_PRICE,AREA_encoded,SALE_COND_encoded,PARK_FACIL_encoded,BUILDTYPE_encoded,UTILITY_AVAIL_encoded,STREET_encoded,MZZONE_encoded
PRT_ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,
P03210,Karapakkam,1004,04-05-2011,131,1.0,1.0,3,AbNormal,Yes,15-05-1967,Commercial,All Pub,Paved,A,4.0,3.9,4.9,4.330,380000,144400,7600000,4,0,1,0,0,2,0
P09411,Anna Nagar,1986,19-12-2006,26,2.0,1.0,5,AbNormal,No,22-12-1995,Commercial,All Pub,Gravel,RH,4.9,4.2,2.5,3.765,760122,304049,21717770,1,0,0,0,0,0,3
P01812,Adyar,909,04-02-2012,70,1.0,1.0,3,AbNormal,Yes,09-02-1992,Commercial,ELO,Gravel,RL,4.1,3.8,2.2,3.090,421094,92114,13159200,0,0,1,0,1,0,4
P05346,Velachery,1855,13-03-2010,14,3.0,2.0,5,Family,No,18-03-1988,Others,NoSeWa,Paved,I,4.7,3.9,3.6,4.010,356321,77042,9630290,6,2,0,2,2,2,2
P06210,Karapakkam,1226,05-10-2009,84,1.0,1.0,3,AbNormal,Yes,13-10-1979,Others,All Pub,Gravel,C,3.0,2.5,4.1,3.290,237000,74063,7406250,4,0,1,2,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P03834,Karapakkam,598,03-01-2011,51,1.0,1.0,2,AdjLand,No,15-01-1962,Others,ELO,No Access,RM,3.0,2.2,2.4,2.520,208767,107060,5353000,4,1,0,2,1,1,5
P10000,Velachery,1897,08-04-2004,52,3.0,2.0,5,Family,Yes,11-04-1995,Others,NoSeWa,No Access,RH,3.6,4.5,3.3,3.920,346191,205551,10818480,6,2,1,2,2,1,3
P09594,Velachery,1614,25-08-2006,152,2.0,1.0,4,Normal Sale,No,01-09-1978,House,NoSeWa,Gravel,I,4.3,4.2,2.9,3.840,317354,167028,8351410,6,3,0,1,2,0,2
P06508,Karapakkam,787,03-08-2009,40,1.0,1.0,2,Partial,Yes,11-08-1977,Commercial,ELO,Paved,RL,4.6,3.8,4.1,4.160,425350,119098,8507000,4,4,1,0,1,2,4
P09794,Velachery,1896,13-07-2005,156,3.0,2.0,5,Partial,Yes,24-07-1961,Others,ELO,Paved,I,3.1,3.5,4.3,3.640,349177,79812,9976480,6,4,1,2,1,2,2

In [45]:
df["DATE_SALE"] = pd.to_datetime(df["DATE_SALE"], dayfirst=True, errors="coerce")

In [46]:
df["DATE_SALE_DETAILS"] = (
    df["DATE_SALE"].dt.strftime('%d-%m-%Y') +
    " | Day:" + df["DATE_SALE"].dt.day.astype(str) +
    " | Month:" + df["DATE_SALE"].dt.month.astype(str) +
    " | Year:" + df["DATE_SALE"].dt.year.astype(str) +
    " | Week:" + df["DATE_SALE"].dt.isocalendar().week.astype(str)
) # This line constructs a new column like:"21-02-2020 | Day:21 | Month:2 | Year:2020 | Week:8"

In [47]:
df

,AREA,INT_SQFT,DATE_SALE,DIST_MAINROAD,N_BEDROOM,N_BATHROOM,N_ROOM,SALE_COND,PARK_FACIL,DATE_BUILD,BUILDTYPE,UTILITY_AVAIL,STREET,MZZONE,QS_ROOMS,QS_BATHROOM,QS_BEDROOM,QS_OVERALL,REG_FEE,COMMIS,SALES_PRICE,AREA_encoded,SALE_COND_encoded,PARK_FACIL_encoded,BUILDTYPE_encoded,UTILITY_AVAIL_encoded,STREET_encoded,MZZONE_encoded,DATE_SALE_DETAILS
PRT_ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
P03210,Karapakkam,1004,2011-05-04,131,1.0,1.0,3,AbNormal,Yes,15-05-1967,Commercial,All Pub,Paved,A,4.0,3.9,4.9,4.330,380000,144400,7600000,4,0,1,0,0,2,0,04-05-2011 | Day:4 | Month:5 | Year:2011 | Wee...
P09411,Anna Nagar,1986,2006-12-19,26,2.0,1.0,5,AbNormal,No,22-12-1995,Commercial,All Pub,Gravel,RH,4.9,4.2,2.5,3.765,760122,304049,21717770,1,0,0,0,0,0,3,19-12-2006 | Day:19 | Month:12 | Year:2006 | W...
P01812,Adyar,909,2012-02-04,70,1.0,1.0,3,AbNormal,Yes,09-02-1992,Commercial,ELO,Gravel,RL,4.1,3.8,2.2,3.090,421094,92114,13159200,0,0,1,0,1,0,4,04-02-2012 | Day:4 | Month:2 | Year:2012 | Week:5
P05346,Velachery,1855,2010-03-13,14,3.0,2.0,5,Family,No,18-03-1988,Others,NoSeWa,Paved,I,4.7,3.9,3.6,4.010,356321,77042,9630290,6,2,0,2,2,2,2,13-03-2010 | Day:13 | Month:3 | Year:2010 | We...
P06210,Karapakkam,1226,2009-10-05,84,1.0,1.0,3,AbNormal,Yes,13-10-1979,Others,All Pub,Gravel,C,3.0,2.5,4.1,3.290,237000,74063,7406250,4,0,1,2,0,0,1,05-10-2009 | Day:5 | Month:10 | Year:2009 | We...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P03834,Karapakkam,598,2011-01-03,51,1.0,1.0,2,AdjLand,No,15-01-1962,Others,ELO,No Access,RM,3.0,2.2,2.4,2.520,208767,107060,5353000,4,1,0,2,1,1,5,03-01-2011 | Day:3 | Month:1 | Year:2011 | Week:1
P10000,Velachery,1897,2004-04-08,52,3.0,2.0,5,Family,Yes,11-04-1995,Others,NoSeWa,No Access,RH,3.6,4.5,3.3,3.920,346191,205551,10818480,6,2,1,2,2,1,3,08-04-2004 | Day:8 | Month:4 | Year:2004 | Wee...
P09594,Velachery,1614,2006-08-25,152,2.0,1.0,4,Normal Sale,No,01-09-1978,House,NoSeWa,Gravel,I,4.3,4.2,2.9,3.840,317354,167028,8351410,6,3,0,1,2,0,2,25-08-2006 | Day:25 | Month:8 | Year:2006 | We...
P06508,Karapakkam,787,2009-08-03,40,1.0,1.0,2,Partial,Yes,11-08-1977,Commercial,ELO,Paved,RL,4.6,3.8,4.1,4.160,425350,119098,8507000,4,4,1,0,1,2,4,03-08-2009 | Day:3 | Month:8 | Year:2009 | Wee...
P09794,Velachery,1896,2005-07-13,156,3.0,2.0,5,Partial,Yes,24-07-1961,Others,ELO,Paved,I,3.1,3.5,4.3,3.640,349177,79812,9976480,6,4,1,2,1,2,2,13-07-2005 | Day:13 | Month:7 | Year:2005 | We...

In [48]:
df["DATE_BUILD"] = pd.to_datetime(df["DATE_BUILD"], dayfirst=True, errors="coerce")

df["DATE_BUILD_DETAILS"] = (
    df["DATE_BUILD"].dt.strftime('%d-%m-%Y') +
    " | Day:" + df["DATE_BUILD"].dt.day.astype(str) +
    " | Month:" + df["DATE_BUILD"].dt.month.astype(str) +
    " | Year:" + df["DATE_BUILD"].dt.year.astype(str) +
    " | Week:" + df["DATE_BUILD"].dt.isocalendar().week.astype(str)
) # DATE_BUILD_DETAILS column created with required conversions

In [49]:
df

,AREA,INT_SQFT,DATE_SALE,DIST_MAINROAD,N_BEDROOM,N_BATHROOM,N_ROOM,SALE_COND,PARK_FACIL,DATE_BUILD,BUILDTYPE,UTILITY_AVAIL,STREET,MZZONE,QS_ROOMS,QS_BATHROOM,QS_BEDROOM,QS_OVERALL,REG_FEE,COMMIS,SALES_PRICE,AREA_encoded,SALE_COND_encoded,PARK_FACIL_encoded,BUILDTYPE_encoded,UTILITY_AVAIL_encoded,STREET_encoded,MZZONE_encoded,DATE_SALE_DETAILS,DATE_BUILD_DETAILS
PRT_ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
P03210,Karapakkam,1004,2011-05-04,131,1.0,1.0,3,AbNormal,Yes,1967-05-15,Commercial,All Pub,Paved,A,4.0,3.9,4.9,4.330,380000,144400,7600000,4,0,1,0,0,2,0,04-05-2011 | Day:4 | Month:5 | Year:2011 | Wee...,15-05-1967 | Day:15 | Month:5 | Year:1967 | We...
P09411,Anna Nagar,1986,2006-12-19,26,2.0,1.0,5,AbNormal,No,1995-12-22,Commercial,All Pub,Gravel,RH,4.9,4.2,2.5,3.765,760122,304049,21717770,1,0,0,0,0,0,3,19-12-2006 | Day:19 | Month:12 | Year:2006 | W...,22-12-1995 | Day:22 | Month:12 | Year:1995 | W...
P01812,Adyar,909,2012-02-04,70,1.0,1.0,3,AbNormal,Yes,1992-02-09,Commercial,ELO,Gravel,RL,4.1,3.8,2.2,3.090,421094,92114,13159200,0,0,1,0,1,0,4,04-02-2012 | Day:4 | Month:2 | Year:2012 | Week:5,09-02-1992 | Day:9 | Month:2 | Year:1992 | Week:6
P05346,Velachery,1855,2010-03-13,14,3.0,2.0,5,Family,No,1988-03-18,Others,NoSeWa,Paved,I,4.7,3.9,3.6,4.010,356321,77042,9630290,6,2,0,2,2,2,2,13-03-2010 | Day:13 | Month:3 | Year:2010 | We...,18-03-1988 | Day:18 | Month:3 | Year:1988 | We...
P06210,Karapakkam,1226,2009-10-05,84,1.0,1.0,3,AbNormal,Yes,1979-10-13,Others,All Pub,Gravel,C,3.0,2.5,4.1,3.290,237000,74063,7406250,4,0,1,2,0,0,1,05-10-2009 | Day:5 | Month:10 | Year:2009 | We...,13-10-1979 | Day:13 | Month:10 | Year:1979 | W...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P03834,Karapakkam,598,2011-01-03,51,1.0,1.0,2,AdjLand,No,1962-01-15,Others,ELO,No Access,RM,3.0,2.2,2.4,2.520,208767,107060,5353000,4,1,0,2,1,1,5,03-01-2011 | Day:3 | Month:1 | Year:2011 | Week:1,15-01-1962 | Day:15 | Month:1 | Year:1962 | We...
P10000,Velachery,1897,2004-04-08,52,3.0,2.0,5,Family,Yes,1995-04-11,Others,NoSeWa,No Access,RH,3.6,4.5,3.3,3.920,346191,205551,10818480,6,2,1,2,2,1,3,08-04-2004 | Day:8 | Month:4 | Year:2004 | Wee...,11-04-1995 | Day:11 | Month:4 | Year:1995 | We...
P09594,Velachery,1614,2006-08-25,152,2.0,1.0,4,Normal Sale,No,1978-09-01,House,NoSeWa,Gravel,I,4.3,4.2,2.9,3.840,317354,167028,8351410,6,3,0,1,2,0,2,25-08-2006 | Day:25 | Month:8 | Year:2006 | We...,01-09-1978 | Day:1 | Month:9 | Year:1978 | Wee...
P06508,Karapakkam,787,2009-08-03,40,1.0,1.0,2,Partial,Yes,1977-08-11,Commercial,ELO,Paved,RL,4.6,3.8,4.1,4.160,425350,119098,8507000,4,4,1,0,1,2,4,03-08-2009 | Day:3 | Month:8 | Year:2009 | Wee...,11-08-1977 | Day:11 | Month:8 | Year:1977 | We...
P09794,Velachery,1896,2005-07-13,156,3.0,2.0,5,Partial,Yes,1961-07-24,Others,ELO,Paved,I,3.1,3.5,4.3,3.640,349177,79812,9976480,6,4,1,2,1,2,2,13-07-2005 | Day:13 | Month:7 | Year:2005 | We...,24-07-1961 | Day:24 | Month:7 | Year:1961 | We...

In [50]:
df["BUILDING_AGE"] = (
    (df["DATE_SALE"] - df["DATE_BUILD"]).dt.days // 365
).astype(str) + " years | " + (
    (df["DATE_SALE"] - df["DATE_BUILD"]).dt.days
).astype(str) + " days"
# Building age calculated

In [51]:
df

,AREA,INT_SQFT,DATE_SALE,DIST_MAINROAD,N_BEDROOM,N_BATHROOM,N_ROOM,SALE_COND,PARK_FACIL,DATE_BUILD,BUILDTYPE,UTILITY_AVAIL,STREET,MZZONE,QS_ROOMS,QS_BATHROOM,QS_BEDROOM,QS_OVERALL,REG_FEE,COMMIS,SALES_PRICE,AREA_encoded,SALE_COND_encoded,PARK_FACIL_encoded,BUILDTYPE_encoded,UTILITY_AVAIL_encoded,STREET_encoded,MZZONE_encoded,DATE_SALE_DETAILS,DATE_BUILD_DETAILS,BUILDING_AGE
PRT_ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
P03210,Karapakkam,1004,2011-05-04,131,1.0,1.0,3,AbNormal,Yes,1967-05-15,Commercial,All Pub,Paved,A,4.0,3.9,4.9,4.330,380000,144400,7600000,4,0,1,0,0,2,0,04-05-2011 | Day:4 | Month:5 | Year:2011 | Wee...,15-05-1967 | Day:15 | Month:5 | Year:1967 | We...,44 years | 16060 days
P09411,Anna Nagar,1986,2006-12-19,26,2.0,1.0,5,AbNormal,No,1995-12-22,Commercial,All Pub,Gravel,RH,4.9,4.2,2.5,3.765,760122,304049,21717770,1,0,0,0,0,0,3,19-12-2006 | Day:19 | Month:12 | Year:2006 | W...,22-12-1995 | Day:22 | Month:12 | Year:1995 | W...,11 years | 4015 days
P01812,Adyar,909,2012-02-04,70,1.0,1.0,3,AbNormal,Yes,1992-02-09,Commercial,ELO,Gravel,RL,4.1,3.8,2.2,3.090,421094,92114,13159200,0,0,1,0,1,0,4,04-02-2012 | Day:4 | Month:2 | Year:2012 | Week:5,09-02-1992 | Day:9 | Month:2 | Year:1992 | Week:6,20 years | 7300 days
P05346,Velachery,1855,2010-03-13,14,3.0,2.0,5,Family,No,1988-03-18,Others,NoSeWa,Paved,I,4.7,3.9,3.6,4.010,356321,77042,9630290,6,2,0,2,2,2,2,13-03-2010 | Day:13 | Month:3 | Year:2010 | We...,18-03-1988 | Day:18 | Month:3 | Year:1988 | We...,22 years | 8030 days
P06210,Karapakkam,1226,2009-10-05,84,1.0,1.0,3,AbNormal,Yes,1979-10-13,Others,All Pub,Gravel,C,3.0,2.5,4.1,3.290,237000,74063,7406250,4,0,1,2,0,0,1,05-10-2009 | Day:5 | Month:10 | Year:2009 | We...,13-10-1979 | Day:13 | Month:10 | Year:1979 | W...,30 years | 10950 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P03834,Karapakkam,598,2011-01-03,51,1.0,1.0,2,AdjLand,No,1962-01-15,Others,ELO,No Access,RM,3.0,2.2,2.4,2.520,208767,107060,5353000,4,1,0,2,1,1,5,03-01-2011 | Day:3 | Month:1 | Year:2011 | Week:1,15-01-1962 | Day:15 | Month:1 | Year:1962 | We...,49 years | 17885 days
P10000,Velachery,1897,2004-04-08,52,3.0,2.0,5,Family,Yes,1995-04-11,Others,NoSeWa,No Access,RH,3.6,4.5,3.3,3.920,346191,205551,10818480,6,2,1,2,2,1,3,08-04-2004 | Day:8 | Month:4 | Year:2004 | Wee...,11-04-1995 | Day:11 | Month:4 | Year:1995 | We...,9 years | 3285 days
P09594,Velachery,1614,2006-08-25,152,2.0,1.0,4,Normal Sale,No,1978-09-01,House,NoSeWa,Gravel,I,4.3,4.2,2.9,3.840,317354,167028,8351410,6,3,0,1,2,0,2,25-08-2006 | Day:25 | Month:8 | Year:2006 | We...,01-09-1978 | Day:1 | Month:9 | Year:1978 | Wee...,28 years | 10220 days
P06508,Karapakkam,787,2009-08-03,40,1.0,1.0,2,Partial,Yes,1977-08-11,Commercial,ELO,Paved,RL,4.6,3.8,4.1,4.160,425350,119098,8507000,4,4,1,0,1,2,4,03-08-2009 | Day:3 | Month:8 | Year:2009 | Wee...,11-08-1977 | Day:11 | Month:8 | Year:1977 | We...,32 years | 11680 days
P09794,Velachery,1896,2005-07-13,156,3.0,2.0,5,Partial,Yes,1961-07-24,Others,ELO,Paved,I,3.1,3.5,4.3,3.640,349177,79812,9976480,6,4,1,2,1,2,2,13-07-2005 | Day:13 | Month:7 | Year:2005 | We...,24-07-1961 | Day:24 | Month:7 | Year:1961 | We...,44 years | 16060 days